language: node_js
node_js:
  - "lts/*"
addons:
  sonarcloud:
    organization: "discipl" # the key of the org you chose at step #3
script:
  - npm test
  # other script steps might be done before running the actual analysis
  - sonar-scanner
